platform :ios, '8.0'

#source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/XLsn0w/Specs.git‘

use_frameworks!

target 'RACDemo' do
  
  pod 'XLsn0wKits'
  
  pod 'ReactiveObjC'
#  pod 'ReactiveSwift'
#  pod 'RxSwift'
  pod 'CTMediator'
  
end

